export default [
  { ind: 0, name: 'Старт', },
  { ind: 1, name: 'Кафе', price: 20, family: 1, },
  { ind: 2, name: 'Бар', price: 30, family: 1, },
  { ind: 3, name: 'Пропуск хода', },
  { ind: 4, name: 'Ресторан', price: 30, family: 1, },
  { ind: 5, name: 'Налог 10%', },
  { ind: 6, name: 'ЖД перевозки', price: 70, family: 2, },
  { ind: 7, name: 'Рекламное агенство', price: 40, family: 3, },
  { ind: 8, name: 'Лотерея', },
  { ind: 9, name: 'Модельное агенство', price: 40, family: 4, },
  { ind: 10, name: 'Тур агенство', price: 40, family: 4, },
  { ind: 11, name: 'Тюрьма', },
  { ind: 33, name: 'Алмазы', price: 200, family: 10, },
  { ind: 12, name: 'Табачная фабрика', price: 50, family: 4, },
  { ind: 32, name: 'Золото', price: 150, family: 10, },
  { ind: 13, name: 'Пивзавод', price: 50, family: 4, },
  { ind: 31, name: 'Налог 20%', },
  { ind: 14, name: 'Ночной клуб', price: 60, family: 5, },
  { ind: 30, name: 'Багамы', price: 120, family: 9, },
  { ind: 15, name: 'Лотерея', },
  { ind: 29, name: 'Гаваи', price: 120, family: 9, },
  { ind: 16, name: 'Казино', price: 60, family: 5, },
  { ind: 28, name: 'Джек пот', },
  { ind: 27, name: 'Хоккейный клуб', price: 70, family: 6, },
  { ind: 26, name: 'Баскет<wbr>больный клуб', price: 70, family: 6, },
  { ind: 25, name: 'Налог 10%', },
  { ind: 24, name: 'Фут<wbr>больный клуб', price: 70, family: 6, },
  { ind: 23, name: 'Авиа<wbr>перевозки', price: 70, family: 2, },
  { ind: 22, name: 'Пропуск хода', },
  { ind: 21, name: 'Авто<wbr>строение', price: 80, family: 7, },
  { ind: 20, name: 'Авиа<wbr>строение', price: 80, family: 7, },
  { ind: 19, name: 'Добыча нефти', price: 90, family: 8, },
  { ind: 18, name: 'Добыча Газа', price: 90, family: 8, },
  { ind: 17, name: 'Отдых', },
]