export default [
  { name: 'Старт' },
  { name: 'Кафе', price: 20, family: 1 },
  { name: 'Бар', price: 30, family: 1 },
  { name: 'Пропуск хода' },
  { name: 'Ресторан', price: 30, family: 1 },
  { name: 'Налог 10%' },
  { name: 'ЖД перевозки', price: 70, family: 2 },
  { name: 'Рекламное агенство', price: 40, family: 3 },
  { name: 'Лотерея' },
  { name: 'Модельное агенство', price: 40, family: 4 },
  { name: 'Тур агенство', price: 40, family: 4 },
  { name: 'Тюрьма' },
  { name: 'Алмазы', price: 200, family: 10 },
  { name: 'Табачная фабрика', price: 50, family: 4 },
  { name: 'Золото', price: 150, family: 10 },
  { name: 'Пивзавод', price: 50, family: 4 },
  { name: 'Налог 20%' },
  { name: 'Ночной клуб', price: 60, family: 5 },
  { name: 'Багамы', price: 120, family: 9 },
  { name: 'Лотерея' },
  { name: 'Гаваи', price: 120, family: 9 },
  { name: 'Казино', price: 60, family: 5 },
  { name: 'Джек пот' },
  { name: 'Хоккейный клуб', price: 70, family: 6 },
  { name: 'Баскет<wbr>больный клуб', price: 70, family: 6 },
  { name: 'Налог 10%' },
  { name: 'Фут<wbr>больный клуб', price: 70, family: 6 },
  { name: 'Авиа<wbr>перевозки', price: 70, family: 2 },
  { name: 'Пропуск хода' },
  { name: 'Авто<wbr>строение', price: 80, family: 7 },
  { name: 'Авиа<wbr>строение', price: 80, family: 7 },
  { name: 'Добыча нефти', price: 90, family: 8 },
  { name: 'Добыча Газа', price: 90, family: 8 },
  { name: 'Отдых' },
]